- README.md
- lib/temporal/client/grpc_client.rb
- lib/temporal/errors.rb
- lib/temporal/testing/temporal_override.rb
- rbi/temporal-ruby.rbi
- spec/unit/lib/temporal/testing_spec.rb
Don't leak GRPC errors outside the client.
More work to do here, this is just low hanging fruit.
> Wrap some GRPC errors.

- lib/temporal/workflow/state_manager.rb
This happens if the Payloads object is missing, rather than present with
an empty payloads array.
> Handle nil payloads.

- examples/middleware/logging_middleware.rb
Previously it was a bit ambigious whether the workflow as a whole was finished versus a single task.
> Make middleware logging clearer.

- lib/temporal/activity/poller.rb
- lib/temporal/worker.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/activity/poller_spec.rb
- spec/unit/lib/temporal/worker_spec.rb
There's a known issue in Temporal (https://github.com/temporalio/temporal/issues/1058) that might drop tasks that are in-transit when canceling a GRPC connection. Temporal will only retry these tasks after a timeout since it's not aware that these were dropped. This can be very confusing and is mostly visible when stopping workers under load.
This simple solution will give in-transit requests a chance to finish (without starting new ones) before canceling pending requests, which should eliminate the majority of occurrences. A proper fix should hopefully land in Temporal server.
> [Fix] Wait before canceling pending requests

- lib/temporal/workflow.rb
- spec/unit/lib/temporal/testing_spec.rb
Minor change to improve hygiene.
Previously, the change to the thread-local context persisted on the main thread in testing mode, making it a bit harder to isolate tests that used `Workflow.execute_locally` from one another.
Test plan:
`rspec ./spec/unit/lib/temporal/testing_spec.rb`
Also ran end-to-end tests in non-testing mode in our environment.
> Make execute_in_context clean up after itself

- lib/temporal/activity/context.rb
- lib/temporal/client/serializer/payload.rb
- lib/temporal/metadata.rb
- lib/temporal/metadata/activity.rb
- lib/temporal/testing/local_workflow_context.rb
- spec/fabricators/activity_metadata_fabricator.rb
- spec/unit/lib/temporal/activity/context_spec.rb
- spec/unit/lib/temporal/metadata/activity_spec.rb
This allows activities to resume where they left off when retring based
on the previously recorded heartbeat details.
> Add support for heartbeat details.

- lib/temporal/configuration.rb
See the comment for justification.
Enqueued a workflow with no override, went to temporal web UI:
> Make execution timeout default to infinite

- lib/temporal/client/grpc_client.rb
- spec/unit/lib/temporal/grpc_client_spec.rb
Previously we would accidentally catch the text following the run id.
Reported by: @drewhoskins-stripe
> Ensure we use a clean RunId.

- lib/temporal/client/grpc_client.rb
- spec/unit/lib/temporal_spec.rb
Without request_id resetting the same workflow twice is not possible due to idempotency protection on this request
> Add request_id to reset_workflow_execution call

- lib/temporal/workflow/history/event.rb
Fixes: NoMethodError: undefined method `scheduled_event_id' for #<Temporal::Api::History::V1::WorkflowExecutionTerminatedEventAttributes:0x000056370c436d38>
> Correct id selection for WorkflowExecutionTerminated event.

- lib/temporal/activity/poller.rb
- lib/temporal/worker.rb
- spec/unit/lib/temporal/worker_spec.rb
We need to temporarily set the thread pool size to 1 so that activities do not run in parallel within a process.  This seems like a useful thing for clients to be able to be able adjust to anyway.
Unit:
`rspec spec/unit/lib/temporal/worker_spec.rb`
> Allow adjusting the activity poller's thread pool size.

- lib/temporal/client/serializer/payload.rb
- spec/unit/lib/temporal/client/serializer/payload_spec.rb
Fixes Encoding::UndefinedConversionError errors for some UTF characters.
> UTF safety

- lib/temporal/testing/workflow_override.rb
- lib/temporal/workflow/state_manager.rb
* You need to `require 'set'` before using `Set`.
* This is actually needed, but you rarely run into it since usually *someone*
has already done it.
* You'd run into this with extremely minimal examples though (I ran into it
with a minimal worker, in `Workflow::StateManager`).
> `require 'set'` whenever `Set` is used.

- lib/temporal/testing/future_registry.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
This fixes a bug in the FutureRegistry where it passes two arguments to Future.fail when this function takes only one argument. A new test case is also added to cover the case, which can be run with:
rspec spec/unit/lib/temporal/testing/local_workflow_context_spec.rb:87
> Correct arguments to Future.fail by FutureRegistry.fail

- examples/spec/integration/failing_activities_workflow_spec.rb
- examples/workflows/failing_activities_workflow.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/future.rb
- spec/unit/lib/temporal/workflow/future_spec.rb
Currently, the futures used for asynchronous execution of activities only call the block passed to `.done` when the activity succeeds. This change makes it possible to have a block called when the activity fails by calling `.failed`. This change is backward compatible with the existing API.
Modified spec for a workflow that uses the activity futures
```
pushd examples
rspec spec/integration/failing_activities_workflow_spec.rb
popd
```
> Callback for when a future fails

- lib/temporal/testing/local_activity_context.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
Unblocks product engineers calling activities that `heartbeat` in local testing mode.
`bundle exec rspec spec/unit/lib/temporal/testing/local_workflow_context_spec.rb`
> Allow heartbeats in local testing mode

- lib/temporal/errors.rb
- lib/temporal/workflow/history/event_target.rb
- lib/temporal/workflow/state_manager.rb
- lib/temporal/workflow/task_processor.rb
This is a port of a bug fix from cadence-ruby: https://github.com/coinbase/cadence-ruby/pull/13
This change ensures that when a workflow is replayed all the commands match previously made ones. If not, a Temporal::NonDeterministicWorkflowError will be raised during execution which will fail the workflow task. While deterministic workflows remain running and enter a bad state, they can now be recovered from this state and the failure is logged in workflow history.
- Existing specs continue to pass:
`rspec`
`pushd examples && rspec && popd`
- Manually tested that existing workflow worker continues to run as expected, verified that a non-deterministic workflow produces the expected error and can resume after code is corrected
> Workflow determinism check

- lib/temporal/retry_policy.rb
- spec/unit/lib/temporal/retry_policy_spec.rb
* When there are no retries, it shouldn't be necessary to set the other retry policy parameters.  I think `nil` will be less confusing than a bunch of values that aren't actually used.
* `expiration_interval` is unused
* temporal allows max_attempts to be nil, see https://docs.temporal.io/docs/go/retries/
New test of a "clean" no-retry policy and an unlimited-attempts policy:
```bundle exec rspec spec/unit/lib/temporal/retry_policy_spec.rb```
> Changes to retry policy validation

- lib/temporal/activity/poller.rb
Reusing the same GRPC connection will increase the performance and reduce the load on the Temporal server — it gets created and goes through a handshake otherwise, which can be expensive. GRPC is thread-safe and expects connection reuse
Tested under load against the Temporal Cloud instance.
> Reuse GRPC connection for Activity processing

- lib/temporal/activity/poller.rb
- lib/temporal/worker.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/worker_spec.rb
Make workflow poller use a thread pool similar to activity poller. In a high load scenario communication with the Temporal server can get slow which makes workflow poller quite inefficient. The workflow processing itself is CPU bound, however performance analysis has shown that majority of that time is spent sending the response back to Temporal.
This change will allow multiple workflow tasks to be processed concurrently increasing the efficiency.
Tested under heavy load against Temporal Cloud achieving a throughput of 1k workflows per second.
> Enable workflow poller thread pool

- lib/temporal/workflow/task_processor.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
When a workflow task fails, only the first failure will now be reported to Temporal server. After the first attempt, subsequent failed tasks will instead time out, reducing how quickly failed tasks are retried to the workflow task timeout.
This reduces load on Temporal server and prevents the task queue from being overwhelmed by retries. This can occur when bad code is deployed that causes the tasks of many workflows to fail. This new retry limit is consistent with the [Go](https://github.com/temporalio/sdk-go/blob/6580cbe0aa41a8b515791f95c2c15bb37db1dab1/internal/internal_task_pollers.go#L380-L381) and [Java](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java#L142-L144) SDKs and is recommended by …
> Reduce workflow task failure reporting retries from 10 to 1

- .circleci/config.yml
- examples/bin/register_namespace
- examples/init.rb
- examples/spec/helpers.rb
- examples/spec/integration/serial_hello_world_workflow_spec.rb
- examples/spec/spec_helper.rb
- lib/temporal/client/grpc_client.rb
- spec/unit/lib/temporal/grpc_client_spec.rb
This PR adds support for running specs in CircleCI against a running Temporal server. This allows for implementing true end-to-end specs observing the result and history of the execution
> Integration specs against a running server

- examples/activities/sleep_activity.rb
- lib/temporal/activity/poller.rb
- lib/temporal/activity/task_processor.rb
- lib/temporal/client/retryer.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/client/retryer.rb
* Java SDK's workers retry when trying to report activity completion/failure.  This should increase reliability when the server is down.
* I tried to use the exact backoff policy parameters they use for their default [GrpcRetryer](https://github.com/temporalio/sdk-java/blob/ad8831d4a4d9d257baf3482ab49f1aa681895c0e/temporal-sdk/src/main/java/io/temporal/internal/common/GrpcRetryer.java#L36), see [RpcRetryOptions](https://github.com/temporalio/sdk-java/blob/ad8831d4a4d9d257baf3482ab49f1aa681895c0e/temporal-serviceclient/src/main/java/io/temporal/serviceclient/RpcRetryOptions.java#L32)
It will retry for a minute.  Note that if the retries are longer than the activity timeout, it will be hitting temporal-server fruitlessly.  Temporal handles this gracefully by complaining that the workflow …
> Retryer; Retries on activity completion/failure

- spec/unit/lib/temporal/activity/task_processor_spec.rb
https://github.com/coinbase/temporal-ruby/pull/74 regressed the speed because we added retries and `sleep` to certain code paths.
Observe that this executes quickly:
```
GitHub/temporal-ruby $ bundle exec rspec spec/unit/
...................................................................................................................................................................................................................................................................................
Finished in 1.08 seconds (files took 0.9169 seconds to load)
275 examples, 0 failures
```
> Speed up unit tests that hit the Retryer

- .circleci/config.yml
- examples/bin/register_namespace
Temporal does not currently offer a way to ensure that a namespace registration is available on all shards.
https://community.temporal.io/t/how-to-tell-the-namespace-is-ready-to-be-polled-by-workers/1606
Unconditionally wait 15 seconds (which is the shard cache refresh time) after namespace registration to ensure it's ready when the workers attempt to use it.
> Fix namespace creation issues in CI.

- lib/temporal/client/serializer/retry_policy.rb
- spec/unit/lib/temporal/client/serializer/retry_policy_spec.rb
- spec/unit/lib/temporal/retry_policy_spec.rb
Fixes a bug in the recent serialization changes when non-retriable errors are specified.
`rspec spec/unit/lib/temporal/client/serializer/retry_policy_spec.rb`
> Fix serialization of retry policy

- examples/workflows/long_workflow.rb
- lib/temporal/client/grpc_client.rb
- lib/temporal/concerns/payloads.rb
- lib/temporal/workflow/state_manager.rb
Other SDKs only use the first payload, as for details/results.
> Special case signal payloads.

- lib/temporal/client/retryer.rb
- spec/unit/lib/temporal/client/retryer.rb
I noticed that we kept retrying activity task reporting even if the activity task had already timed out, which eats a thread for a considerable amount of time while it keeps retrying.
There are a lot of exceptions that there's no need to retry.
New unit test:
```
drewhoskins/stripe/temporal-ruby $ bundle exec rspec -f d ./spec/unit/lib/temporal/client/retryer.rb
Temporal::Client::Retryer
backs off and stops retrying eventually
caps out amount slept
can succeed
can succeed after retries
executes the on_retry callback
does not retry GRPC::AlreadyExists
does not retry GRPC::Cancelled
does not retry GRPC::FailedPrecondition
does not retry GRPC::InvalidArgument
does not retry GRPC::NotFound
does not retry GRPC::PermissionDenied
does not retry GRPC::Unauthenticated
does not retry …
```
> Blocklist certain exceptions from task retries

- lib/temporal/json.rb
- spec/unit/lib/temporal/client/converter/payload/json_spec.rb
Timestamps I was using for high-precision cursoring were getting truncated.
This approach gets the correct answer, the disadvantage being that when the numbers get weird enough, it switches to scientific notation.
e.g. `1626122511.3059866` becomes `0.16261225113059866e10`
Certainly an improvement over `1626122511.30599` which was what happened before.
`bundle exec rspec spec/unit/lib/temporal/client/converter/payload/json_spec.rb`
> Fix float serialization roundtrip

- CONTRIBUTING.md
- README.md
- examples/README.md
Syncing https://github.com/coinbase/cadence-ruby/pull/44
This fixes a couple spelling mistakes and a broken link.
> Fix documentation spelling and broken link

- examples/spec/helpers.rb
- lib/temporal.rb
- lib/temporal/client.rb
- lib/temporal/testing.rb
- spec/unit/lib/temporal/client_spec.rb
- spec/unit/lib/temporal/testing/temporal_override_spec.rb
- spec/unit/lib/temporal_spec.rb
This is syncing https://github.com/coinbase/cadence-ruby/pull/42.
Quoting Anthony's PR description:
"
This turns ~~`Cadence`~~ Temporal into an initializable ~~`Cadence::Client`~~ `Temporal::Client` allowing to connect to multiple clusters:
```
config_1 = Temporal::Configuration.new
config_1.host = 'xxx'
client_1 = Temporal::Client.new(config_1)
client_1.start_workflow(TestWorkflow)
config_2 = Temporal::Configuration.new
config_2.host = 'xxx'
client_2 = Temporal::Client.new(config_2)
client_2.start_workflow(TestWorkflow)
```
This change is backwards compatible and ~~`Cadence.*`~~ `Temporal.*` class methods are simply delegated to a default client.
The "meat" of this PR is moving ~~`Cadence`~~ `Temporal` methods into ~~`Cadence::Client`~~ `Temporal::Client` and moving specs
"
> [Feature] Initializable Temporal client

- .gitignore
- lib/temporal/client.rb
- lib/temporal/reset_strategy.rb
- lib/temporal/workflow/history.rb
- spec/fabricators/grpc/history_event_fabricator.rb
- spec/unit/lib/temporal/client_spec.rb
Syncing [#48](https://github.com/coinbase/cadence-ruby/pull/48).
Original PR Description:
"
This change would allow specifying a strategy when resetting a workflow. This is very useful when resetting a batch of workflows that all might have failed at different points in history
~~Tested against a running server & specs updated to reflect the change~~
"
> Implement strategies for resetting workflows

- lib/temporal/errors.rb
- lib/temporal/workflow/task_processor.rb
- spec/fabricators/grpc/workflow_task_fabricator.rb
- spec/fabricators/workflow_execution_history_fabricator.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
We have observed a weird case when a workflow task was handled incorrectly resulting in non-deterministic commands getting sent back to Temporal and corrupting a workflow execution. Our suspicion is that Temporal API has responded with a blank history to one of the GetWorkflowExecutionHistory calls.
The added check should help us confirm the issue and protect from the negative side effects.
Tested by added new test cases.
> [Feature] Fail workflow task when empty history page was received

- lib/temporal/client.rb
- spec/unit/lib/temporal/client_spec.rb
Allow a namespace to be specified when signalling a workflow.
There was no CI test coverage of signal_workflow, so we added a basic test as well as one with a namespace.
`rspec ./spec/unit/lib/temporal/client_spec.rb`
> Support signaling workflows in a namespace

- lib/temporal/metadata.rb
- lib/temporal/metadata/workflow.rb
- lib/temporal/testing/temporal_override.rb
- lib/temporal/testing/workflow_override.rb
- lib/temporal/workflow/executor.rb
- lib/temporal/workflow/state_manager.rb
- lib/temporal/workflow/task_processor.rb
- spec/fabricators/workflow_metadata_fabricator.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
- spec/unit/lib/temporal/metadata/workflow_spec.rb
- spec/unit/lib/temporal/metadata_spec.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
- spec/unit/lib/temporal/workflow/executor_spec.rb
This is syncing https://github.com/coinbase/cadence-ruby/pull/60
Original PR description:
```
There are 3 types of metadata — decision, activity and workflow. Each is exposed to different parts of the SDK.
Workflow ID is generated from the history, which confusingly doesn't have domain or workflow_id. This PR adds these 2 missing fields from the decision metadata
Tested using unit specs and manual workflow runs
```
> [Feature] Add id and domain to workflow context's metadata

- examples/.env
By default docker-compose uses the name of the directory hosting the `docker-compose.yml` file (`examples` in this case), which can then generate ambiguous containers (it clashes with cadence-ruby/examples if you use both)
> Explicit docker-compose project name

- README.md
- lib/temporal/client.rb
- temporal.gemspec
Adds a YARD-style documentation for the project which can be viewed over at https://rubydoc.info/github/coinbase/temporal-ruby
> Add YARD documentation for Temporal::Client

- examples/bin/worker
- examples/spec/integration/wait_for_workflow_spec.rb
- examples/workflows/wait_for_workflow.rb
- lib/temporal/testing/local_workflow_context.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/dispatcher.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
- spec/unit/lib/temporal/workflow/dispatcher_spec.rb
Extends the `wait_for` method on workflow context to take multiple futures and a condition block. This provides the equivalent to [`Workflow.await` in Java](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java#L822) and [`workflow.Await` in Go](https://pkg.go.dev/go.temporal.io/sdk@v1.11.0/workflow#Await) and a "wait for any" function. This function blocks workflow progress until one of the futures is finished or the block returns true. It can be used for a variety of cases where a workflow needs to wait for the completion of any combination of activities or timer completion, or receipt of a signal.
Also included:
- A new `WaitForWorkflow` example that demonstrates all three of these cases, along with an integration test to run …
> Extend wait_for on workflow context to take multiple futures and a condition block

- lib/temporal/workflow/context.rb
- lib/temporal/workflow/dispatcher.rb
- lib/temporal/workflow/history/event_target.rb
- spec/unit/lib/temporal/workflow/dispatcher_spec.rb
During registration, the `Dispatcher` places all dispatch targets into a hash keyed on target. Before https://github.com/coinbase/temporal-ruby/pull/111, event targets were always of type `EventTarget`. With that change, event targets could also be of type `String` (i.e., `"*"`). In the implementation of `Hash`, objects of these two types can be compared using the `eql?` method when they end up in the same bucket behind the scenes. `EventTarget.eql?` can only compare objects that have an `id` and `type` field like itself. Because a `String` does not have these fields, it sometimes fails with a specific error while trying to register a dispatch handler:
```
Failure/Error: id == other.id && type == other.type
NoMethodError:
undefined method `id' for "*":String
```
- Modifies …
> Fix EventTarget comparison with wildcard

- lib/temporal/configuration.rb
- spec/unit/lib/temporal/configuration_spec.rb
As shown in the comments, the temporal team strongly recommends against using `schedule_to_start` timeout unless you're doing things like manually re-routing to different task queues.
We have also run into struggles with this timeout.  I think the best policy is to remove the default.
`bundle exec rspec ./spec/unit/lib/temporal/configuration_spec.rb`
> Turn off schedule_to_start activity timeout by default

- lib/temporal/client.rb
This change should not affect the behaviour in any way, but it makes a split between `options:` and `**args` a bit more visible and fixes documentation (right now it's not showing different options available because there isn't an `options:` input arg).
The unchanged behaviour and API should be guaranteed by the specs that we have in place (e.g. `spec/unit/lib/temporal/client_spec.rb:96`)
> Separate options from keyword args in #start_workflow

- examples/spec/integration/continue_as_new_spec.rb
- examples/spec/integration/metadata_workflow_spec.rb
- examples/workflows/loop_workflow.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/connection/serializer/continue_as_new.rb
- lib/temporal/connection/serializer/start_child_workflow.rb
- lib/temporal/workflow/context.rb
- spec/unit/lib/temporal/connection/serializer/continue_as_new_spec.rb
This contains two improvements to headers, both of which change the behavior of workflow headers:
First, headers are now by default propagated to the next run of a workflow on continue-as-new. This can be overridden by passing `options: {headers: overridden_headers}` to `workflow.continue_as_new` if desired.
Second, to set headers, you no longer need to use the generated proto classes. Instead, you can simply pass an ordinary hash, which will be automatically serialized into the proper proto. This makes the use of headers more ergonomic and eliminates the need to use the lower-level protobuf abstraction in code that uses temporal-ruby. However, **this is a breaking change**. If you are currently passing protobuf objects in for headers, you will need to instead pass a hash.
The …
> Improve header serialization and propagation

- examples/spec/integration/activity_cancellation_spec.rb
- examples/workflows/long_workflow.rb
- lib/temporal/errors.rb
- lib/temporal/workflow/history/event_target.rb
- lib/temporal/workflow/state_manager.rb
- spec/fabricators/grpc/history_event_fabricator.rb
- spec/unit/lib/temporal/workflow/history/event_target_spec.rb
When an activity cancellation is requested before the activity had a chance to start Temporal will issue an `ACTIVITY_CANCELED` event. This PR fixed handling of this event.
Tested:
- Added both unit & integration specs to ensure it works as expected
> [Fix] Non-started activity cancellation

- examples/spec/integration/start_workflow_spec.rb
- lib/temporal/execution_options.rb
Fixes #123 
This is a weird issue, but it seems that `Object#singleton_class` does something to the object and screws up class detection in C extensions (used by Protobufs). Here's an example:
```ruby
>> a = 'TestWorkflow'
=> "TestWorkflow"
>> a.singleton_class
=> #<Class:#<String:0x000000013320dc10>>
>> Temporal::Api::Common::V1::WorkflowType.new(name: a)
(irb):3:in `initialize': Invalid argument for string field 'name' (given String). (Google::Protobuf::TypeError)
from (irb):3:in `new'
from (irb):3:in `<main>'
from /opt/homebrew/Cellar/rbenv/1.1.2/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/cli/console.rb:19:in `run'
from /opt/homebrew/Cellar/rbenv/1.1.2/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/lib/bundler/cli.rb:504:in `console'
from …
```
> [Fix] Workflow scheduling using a String

- examples/spec/helpers.rb
- examples/spec/integration/describe_namespace_spec.rb
- examples/spec/integration/metadata_workflow_spec.rb
It can take some time between registering a namespace, and that namespace being available to describe. Moreover, the test as originally written can depend on the behavior of a previous run. The description passed on initial namespace registration will remain on the namespace indefinitely. If this value is changed in code, subsequent tests will fail when the description does not match.
Using ruby-samples (or whatever name has been overridden in an environment variable) ensures the same behavior each run and is not subject to the possible delay of creating a new namespace since this namespace must already exist to be able to start the test workers.
This fixes flaky CI failures such as https://app.circleci.com/pipelines/github/coinbase/temporal-ruby/352/workflows/171da02d-adb6-44f1-b203-ae1fc …
> Change describe_namespace integration spec to use the default namespace

- lib/temporal/workflow/errors.rb
- spec/unit/lib/temporal/workflow/errors_spec.rb
https://github.com/coinbase/temporal-ruby/pull/103 lets temporal-ruby respond gracefully when it can't construct the correct exception from serialized data. This PR makes that logic kick in for any type of deserialization failure, not just ArgumentError
I added a test to this unit: `bundle exec rspec ./spec/unit/lib/temporal/workflow/errors_spec.rb`
Integration, to check for regressions:
```
cd examples
./bin/worker &
USE_ENCRYPTION=1 ./bin/worker &
```
> Make error deserialization more resilient

- README.md
- removed metacharacters from the shell commands so they can be
copy/pasted directly
- added require 'temporal-ruby' for each example that needs it
- made it clear that the worker and workflow both need access to
the same configuration step, so it should be its own file
- made it clear the worker and workflow files need to be executed
in their own terminals/shells
> Modify the Getting Started section so that it works

- lib/temporal/activity/task_processor.rb
- lib/temporal/workflow/task_processor.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
This PR adds the namespace as a tag to the metrics that were missing it. The tag name was chosen to be consistent with the  other times it is used with other metrics in the library. This is helpful to be able to tell if a particular namespace is having issues. The current activity/workflow name tag doesn't have enough context.
> Add namespace to emitted metrics

- lib/temporal/activity/task_processor.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
We've found it helpful to tag activity metrics with the workflow name that called them so that we can build a dashboard that includes all related information for a workflow. The tag is named the same as other workflow tags in the library e.g. in the workflow task processor.
This PR also sneaks a fix for a logging typo in too.
> Add workflow tag to metrics emitted from the activity task processor

- lib/temporal/activity/task_processor.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/workflow/task_processor.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
The somewhat recently added `namespace` field on workflow & activity task RPCs is critical for any use of an [Authorizer](https://docs.temporal.io/docs/server/security/#authorizer-plugin-interface).
Without this change, the flow is:
1.  Workflow tasks poll successful
2. [locally] Workflow task started
3. [locally] Workflow task finished
4. Workflow task completed -- `#<GRPC::PermissionDenied: 7:Request unauthorized.>`
5. Workflow task failed (failure is also not being reported to the server)
Related auth code:
https://github.com/temporalio/temporal/blob/3c427e6a2d5e7bcdda5868f379a26f6eb578871f/common/authorization/interceptor.go#L126-L137
> Populate namespace field to all workflow/activity task RPCs

- examples/spec/helpers.rb
- examples/spec/integration/activity_cancellation_spec.rb
- lib/temporal/activity/context.rb
- spec/unit/lib/temporal/activity/context_spec.rb
Add the missing namespace argument to the `record_activity_task_heartbeat` client method. Fixes the `activity_cancellation_spec` failure.
Also refactored the `run_workflow` helper slightly to allow override to `options[:workflow_id]` and modified the failing spec file to use the helper.
> Add missing namespace arg for heartbeat, small helper refactor

- examples/spec/integration/upsert_search_attributes_spec.rb
- examples/workflows/upsert_search_attributes_workflow.rb
- lib/temporal/testing/local_workflow_context.rb
- lib/temporal/testing/temporal_override.rb
- lib/temporal/testing/workflow_execution.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/context_helpers.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
- spec/unit/lib/temporal/testing/temporal_override_spec.rb
- spec/unit/lib/temporal/workflow/context_spec.rb
1) Make it work in local test mode by caching the attributes on `WorkflowExecution`
2) Figured out how to pass a Datetime into temporal and updated the test and docs accordingly
3) Allow people to pass a `Time` in which gets converted under the hood to the appropriate format.
Local testing: `rspec ./spec/unit/lib/temporal/testing/temporal_override_spec.rb`
Integration with datetime: 
```
cd examples
./bin/worker
rspec ./spec/integration/upsert_search_attributes_spec.rb`
```
> Improvements to upsert_search_attributes

- lib/temporal/activity/poller.rb
- lib/temporal/workflow/poller.rb
Upon worker shutdown, we see
```
^CI, [2022-03-01T10:23:31.365933 #37552]  INFO -- temporal_client: Shutting down a workflow poller {}
I, [2022-03-01T10:23:31.366013 #37552]  INFO -- temporal_client: Shutting down a workflow poller {}
I, [2022-03-01T10:23:31.366046 #37552]  INFO -- temporal_client: Shutting down activity poller {"namespace":"ruby-samples","task_queue":"general"}
I, [2022-03-01T10:23:31.366069 #37552]  INFO -- temporal_client: Shutting down activity poller {"namespace":"ruby-samples","task_queue":"file-processing"}
E, [2022-03-01T10:23:32.371431 #37552] ERROR -- temporal_client: Unable to poll Workflow task queue {"namespace":"ruby-samples","task_queue":"general","error":"#<GRPC::Cancelled: 1:Cancelled. debug_error_string:{\"created\":\"@1646159012.369890000\",\"description …
```
> Remove error logspew when workers shutdown

- lib/temporal/workflow/context.rb
PR #121 exposed Memos across the codebase. Though memo was added to `StartChildWorkflow` [here](https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal/connection/serializer/start_child_workflow.rb#L26), it is not actually getting passed from the options in `execute_workflow`. 
This PR just corrects that omission.
> [wip] expose memo for child workflow execution

- lib/temporal/workflow/execution_info.rb
- spec/unit/lib/temporal/workflow/execution_info_spec.rb
list_workflow_executions is currently not working when search attributes object is nil. This PR adds the nil check for `response.search_attributes` to ensure it doesn't blow up.
> Added fix for nil search attributes when listing workflows

- examples/spec/integration/converter_spec.rb
several engineers have been confused by this test, which requires a separate `./bin/worker` to be run.
Catch the workflow timeout and give a better error.
without having run `USE_ENCRYPTION=1 ./bin/worker` ...
```
coinbase/temporal-ruby/examples $ rspec spec/integration/converter_spec.rb 
F
Failures:
1) Converter can encrypt payloads
Failure/Error: raise "Encrypted-payload workflow didn't run.  Make sure you run USE_ENCRYPTION=1 ./bin/worker and try again."
RuntimeError:
Encrypted-payload workflow didn't run.  Make sure you run USE_ENCRYPTION=1 ./bin/worker and try again.
```
> Make it easier to debug converter_spec failure.

- lib/temporal/metadata.rb
- lib/temporal/metadata/activity.rb
- lib/temporal/testing/local_workflow_context.rb
- spec/fabricators/activity_metadata_fabricator.rb
- spec/fabricators/grpc/activity_task_fabricator.rb
- spec/unit/lib/temporal/metadata/activity_spec.rb
This adds two scheduling-related fields to the activity metadata. These are present in the temporal java SDK.
```
bundle exec rspec spec/unit/
cd examples
./bin/worker &
USE_ENCRYPTION=1 ./bin/worker &
```
> Expose scheduled_time and current_attempt_scheduled_time on activity metadata

- examples/spec/integration/register_namespace_spec.rb
- lib/temporal/client.rb
- lib/temporal/connection/grpc.rb
- spec/unit/lib/temporal/client_spec.rb
Currently we can't specify many settings / configs that the register_namespace API provides. This PR adds the ability to set the retention period and the namespace data when registering a namespace with Temporal. 
Also this introduces an integration test (which might be controversial) which registers namespaces and tests the errors. This does create a new namespace which can't be deleted but seems like the only way to integration test this function.
> Updating register namespace

- examples/workflows/parent_close_workflow.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/state_manager.rb
Currently, in order to ensure child workflows behave as expected, we have to wait for temporal to send a ChildExecutionStarted history event. Since we can't do that, we've been sleeping. This PR adds a wait_for_start to child workflow execution so that we can reliably wait for Child workflows, as [indicated in Temporal's docs](https://docs.temporal.io/docs/concepts/what-is-a-child-workflow-execution)
I ran:
```
bundle exec rspec spec/
cd examples
./bin/worker
USE_ENCRYPTION=1 ./bin/worker
```
I modified parent_close_workflow_spec to use this flag instead of sleep. If you disable `wait_for_start`, the test will fail nondeterministically.
> Expose wait_for_start for child workflow execution

- examples/spec/integration/parent_close_workflow_spec.rb
- examples/workflows/slow_child_workflow.rb
- lib/temporal/metadata.rb
- lib/temporal/metadata/workflow.rb
- lib/temporal/testing/temporal_override.rb
- lib/temporal/testing/workflow_override.rb
- spec/fabricators/workflow_metadata_fabricator.rb
- spec/unit/lib/temporal/metadata/workflow_spec.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
- spec/unit/lib/temporal/workflow/executor_spec.rb
Exposing parent_workflow_id and parent_run_id in workflow executions will help with programming child workflows, and improve logging (since workflow metadata is appended to logs). This is mostly just plumbing from temporal's workflow started response.
I modified parent_workflow_spec to return the new metadata field from a child, and asserted that it was correct.
```
bundle exec rspec spec/
cd examples
./bin/worker
USE_ENCRYPTION=1 ./bin/worker
```
> Add parent_run_id, parent_id to workflow metadata

- examples/bin/worker
- examples/spec/integration/named_signal_handler_spec.rb
- examples/workflows/wait_for_named_signal_workflow.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/dispatcher.rb
- lib/temporal/workflow/signal.rb
- lib/temporal/workflow/state_manager.rb
- spec/unit/lib/temporal/workflow/dispatcher_spec.rb
Support for named signal handlers, e.g. `on_signal('SOME_NAME') { }`. Always call the "catch-all" signal handler even when a named handler exists.
> Named signal handlers

- lib/temporal/testing/local_workflow_context.rb
- spec/unit/lib/temporal/testing/local_workflow_context_spec.rb
I was working with activity metadata in unit tests, and noticed that workflow_name was always nil. This behavior doesn't match the behavior outside of tests. This PR brings to the two in line.
I also noticed that the 5th arg to `LocalWorkflowContext.new` was a `Temporal::Metadata::Workflow` [for a parent workflow](https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal/testing/workflow_override.rb#L42) but a hash (the result of `execution_options.headers`) for a child workflow. Now it's a `Temporal::Metadata::Workflow` for both.
> Expose workflow name in activity metadata in temporal-ruby's unit tester

- lib/temporal/testing/local_workflow_context.rb
https://github.com/coinbase/temporal-ruby/pull/130 changed how workflow metadata was constructed in unit test land, and https://github.com/coinbase/temporal-ruby/pull/169 added two required fields on workflow metadata. 130 was written before 169, but merged after 169 (with no merge conflicts). Because 130 doesn't pass the two required fields, unit tests that try to run child workflows locally are currently broken.
Pass the two new required fields to `Workflow::Metadata.new` when running child workflows locally.
```
bundle exec rspec spec/
cd examples
./bin/worker &
USE_ENCRYPTION=1 ./bin/worker &
```
> Fix a merge error between child workflows and metadata enrichment

- lib/temporal.rb
- lib/temporal/client.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/workflow/executions.rb
- spec/unit/lib/temporal/client_spec.rb
- spec/unit/lib/temporal/grpc_spec.rb
Adds the `list_workflow_executions` API to the client (which support searching by the query string [List Filters API](https://docs.temporal.io/docs/temporal-explained/visibility/#list-filters)) and exposes the pagination for `list_open_workflow_executions` and `list_closed_workflow_exceptions`.
```ruby
executions = client.list_workflow_executions(namespace, query)
executions.each { |execution| ... } # iterates through all executions on all pages, loaded lazily
executions = client.list_workflow_executions(namespace, query, max_page_size: 100)
executions.each { |execution| ... } # iterates through a single page only
token = executions.next_page_token # gives you access to the token
executions = client.list_workflow_executions(namespace, query, max_page_size: 100, next_page_token: token) …
```
> Added list workflows API and Pagination Support

- examples/bin/worker
- examples/spec/integration/upsert_search_attributes_spec.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/worker.rb
- lib/temporal/workflow/poller.rb
- lib/temporal/workflow/task_processor.rb
- spec/fabricators/grpc/history_event_fabricator.rb
- spec/unit/lib/temporal/grpc_spec.rb
- spec/unit/lib/temporal/worker_spec.rb
- spec/unit/lib/temporal/workflow/poller_spec.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
Adds binary checksums for propagating information about the binary running workflow tasks into Temporal
This makes it possible to see the version of the worker code that executed a workflow task in temporal-web and tctl. The value is also indexed into elastic search, where it becomes possible to query for all workflows that executed on a certain worker version. Workflow histories can be reset to the last entry before a "bad" version was deployed. Checksums can also be marked as "bad" on a per namespace basis, resulting in Temporal server rejecting polling requests from workers running a "bad" version.
Modified existing specs where binary checksum is propagated down:
```
rspec spec/unit/lib/temporal/grpc_spec.rb
rspec spec/unit/lib/temporal/worker_spec.rb
rspec …
```
> Binary checksum

- lib/temporal/workflow/context.rb
- lib/temporal/workflow/dispatcher.rb
- spec/unit/lib/temporal/workflow/dispatcher_spec.rb
This contains critical follow ups to #111.
Dispatch handlers for `wait_until` are now called in a deterministic order that does not change as a workflow progresses, preventing non-determinism errors from arising where user code is indeed deterministic.
When `wait_until` is called, a dispatch handler is added that resumes the fiber once the condition has been satisfied. Because this condition could change due to any workflow progress, it must be evaluated on every dispatch. Before this change, all `wait_until` handlers were always evaluated after any targeted dispatch callbacks (such as from a specific activity or timer). This can cause non-determinism in certain corner cases. These callbacks are now always called in the same order. This is achieved by associating an autoincrementing, …
> Important performance and correctness fixes for wait_until

- .circleci/config.yml
- README.md
- lib/temporal/configuration.rb
- lib/temporal/connection.rb
- lib/temporal/connection/grpc.rb
- spec/unit/lib/temporal/connection_spec.rb
- spec/unit/lib/temporal/grpc_spec.rb
Closes https://github.com/coinbase/temporal-ruby/issues/70
Third attempt at adding SSL support. Previous attempts died: https://github.com/coinbase/temporal-ruby/pull/73 and https://github.com/coinbase/temporal-ruby/pull/140
Bonus: allows adding OAuth2 tokens using same gRPC credentials.
> Add gRPC credentials

- examples/spec/integration/query_workflow_spec.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/executor.rb
- lib/temporal/workflow/query_registry.rb
- lib/temporal/workflow/stack_trace_tracker.rb
- lib/temporal/workflow/task_processor.rb
- spec/unit/lib/temporal/workflow/context_spec.rb
- spec/unit/lib/temporal/workflow/executor_spec.rb
- spec/unit/lib/temporal/workflow/query_registry_spec.rb
- spec/unit/lib/temporal/workflow/stack_trace_tracker_spec.rb
- Adds a built-in `__stack_trace` query for all workflows that returns the stack trace of all suspended fibers for a workflow
- The error message returned when an unknown query is received now matches that of the Go SDK ([source](https://github.com/temporalio/sdk-go/blob/cee305f568f4b7cba5ec1c597d206bd0114289d7/internal/internal_workflow.go#L550))
- Temporal-web intentionally makes an unknown query `__cadence_web_list`, then parses its error message to extract a list of all registered queries.
- Matching the error message has the effect of enableing a UI in temporal-web for executing queries on the 'Query' tab of a workflow.
If there are multiple fibers suspended, it displays more than one stack trace. Here, we see a workflow that is sleeping in an activity's done callback, while waiting …
> Query functionality for temporal-web: stack trace and registered queries

- examples/spec/integration/signal_with_start_spec.rb
- examples/workflows/signal_with_start_workflow.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/dispatcher.rb
- spec/unit/lib/temporal/workflow/dispatcher_spec.rb
@dwillett discovered a bug in the ordering of the evaluation of `wait_until` handlers that was introduced in https://github.com/coinbase/temporal-ruby/pull/183. The short version is that sometimes workflows end up stuck because a `wait_until` condition evaluates to false before another handler, such as a signal handler, is executed that would change the condition to true. The `wait_until` handler should always be called after the handlers for a specific event have been called.
More details of the bug and its behavior can be found in https://github.com/dwillett/temporal-ruby/pull/3. 
`wait_until` handlers are now called after event-specific handlers, undoing this part of the earlier PR. The behavior of signal handlers that do not specify a name, which also use dispatch target wildcards, …
> Fix dispatch ordering of wait_until handlers

- lib/temporal/configuration.rb
- lib/temporal/connection/converter/payload/proto_json.rb
- spec/unit/lib/temporal/connection/converter/payload/proto_json_spec.rb
https://github.com/coinbase/temporal-ruby/issues/191
> Adds ProtoJSON support for protobuf inputs

- temporal.gemspec
This should prevent the failing specs until the issue is investigated in more detail
> Pin RSpec to 3.10.0

- lib/temporal/configuration.rb
- lib/temporal/connection.rb
- spec/unit/lib/temporal/configuration_spec.rb
- spec/unit/lib/temporal/connection_spec.rb
This change makes two changes in the client identity reported to Temporal server. These identities are used to show active activity and workflow pollers in tctl, temporal-web, and most prominently in the newer temporal-ui. They also appear in workflow histories, indicating where a workflow or activity task was processed.
The first commit makes these identities configurable in the client. This allows a user of temporal-ruby to set whichever arbitrary identity they would like to identify their worker.
The second commit changes the default identity to be based on the process ID (pid) of the worker plus hostname. Prior to this change, the object_id of the current thread was used. Unlike the pid, a current thread's object ID cannot easily be correlated with logs. Moreover, thread IDs are not …
> Derive client identity from pid, make configurable

- lib/temporal/activity/poller.rb
- lib/temporal/activity/task_processor.rb
- lib/temporal/metric_keys.rb
- lib/temporal/thread_pool.rb
- lib/temporal/workflow/poller.rb
- lib/temporal/workflow/task_processor.rb
- spec/unit/lib/temporal/activity/poller_spec.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
- spec/unit/lib/temporal/thread_pool_spec.rb
- spec/unit/lib/temporal/workflow/poller_spec.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
This change emits several new metrics around the processing of workflow and activity tasks. It also consolidates metrics names into constants, in a manner similar to the Java SDK, which makes it easy to see all metrics emitted.
New metrics:
- workflow task failure counter: indicate misversioning and other workflow code defects
- available thread pool size gauge: indicate thread pool utilization
- activity and workflow poll completed counters: indicate performance of pollers, with a special received_task tag indicating if a task was indeed received (or `false` if the call timed out without a task)
> Task metrics

- lib/temporal/configuration.rb
Follow up on feedback from #198 that fixes a couple of outstanding nits:
- Unifies the converter accessor
- Makes `default_identity` private
- Freezes the default identity string
> Unify converter accessor, make default_identity private

- lib/temporal.rb
- lib/temporal/client.rb
- lib/temporal/connection/grpc.rb
- spec/unit/lib/temporal/grpc_spec.rb
This PR fixes implements the count_workflow_executions function. It doesn't directly expose the method, to call it, you will need to do something like
```ruby
Temporal.connection.count_workflow_executions(...)
```
```
bundle exec rspec spec/
cd examples
(terminal 1) ./bin/worker
(terminal 2) USE_ENCRYPTION=1 ./bin/worker
(terminal 3) bundle exec rspec spec/integration
```
> Exposing raw gRPC connection to sdk and count workflow executions

- lib/temporal/execution_options.rb
This is a more refined fix for being able to invoke a workflow by name (#123, originally fixed in #128) that also allows workflows using Sorbet to be declared final (fixing #178). The object is now only dup'd before calling `.singleton_class` if it's a `String`.
Existing tests for starting workflows continue to pass (as do all other tests):
```
bundle exec rspec spec/integration/start_workflow_spec.rb
```
I've also tested that,
- All specs (both unit and integration) pass on protobuf 3.19.1 with grpc 1.41.1. The underlying issue in protobuf for invoking by name was fixed in 3.20.0. 
- A simple workflow whose class and `execute` method are marked as final works without a runtime error. A test for this cannot be checked in without taking a new dependency on the Sorbet runtime. Code that I …
> Test for executable concerns with dup only for String

- examples/spec/integration/search_attributes_spec.rb
- lib/temporal.rb
- lib/temporal/client.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/errors.rb
- spec/unit/lib/temporal/client_spec.rb
- spec/unit/lib/temporal/grpc_spec.rb
Adds add, list, and remove APIs for custom search attributes. Since these operations live on the OperatorService in the GRPC contract, a client for this has also been introduced into `grpc.rb`.
New unit specs at client and GRPC connection level:
```
bundle exec rspec spec/unit/lib/temporal/client_spec.rb:790:804:819
bundle exec rspec spec/unit/lib/temporal/grpc_spec.rb:649:733:789
```
New example specs:
```
bundle exec rspec spec/integration/search_attributes_spec.rb
```
> APIs for managing custom search attributes

- examples/spec/integration/initial_search_attributes_spec.rb
- examples/spec/integration/upsert_search_attributes_spec.rb
- examples/workflows/upsert_search_attributes_workflow.rb
- lib/temporal/workflow/context.rb
- lib/temporal/workflow/state_manager.rb
- spec/fabricators/grpc/history_event_fabricator.rb
- spec/unit/lib/temporal/workflow/context_spec.rb
- spec/unit/lib/temporal/workflow/state_manager_spec.rb
Adds the ability to use `workflow.search_attributes` to read all current search attributes in workflow code
New specs for state_manager:
```
bundle exec rspec spec/unit/lib/temporal/workflow/state_manager_spec.rb:42
```
Updated example specs for initial and upsert search attributes:
```
cd examples
bundle exec rspec spec/integration/initial_search_attributes_spec.rb spec/integration/upsert_search_attributes_spec.rb
```
> Read search attributes from inside workflow code

- examples/bin/register_namespace
- examples/spec/integration/search_attributes_spec.rb
- lib/temporal/errors.rb
- lib/temporal/workflow/task_processor.rb
- spec/fabricators/grpc/workflow_task_fabricator.rb
- spec/fabricators/workflow_execution_history_fabricator.rb
- spec/unit/lib/temporal/workflow/task_processor_spec.rb
Temporal server sometimes sends empty history pages but with a next_page_token.  Best practice across the SDKs is to keep paginating.
But temporal ruby was frequently returning a `Temporal::UnexpectedResponse`. This caused workflow tasks to fail and delay ten seconds until the next retry.  Especially prevalent on long workflow histories.
This change simply removes the check since this is supported behavior.
Update: I threw in a couple of unrelated test fixes to get the CircleCI tests to pass.
Note : I OKed this with Chad Retz from Temporal.  We've had this change active for months at Stripe and have been happy with it.
New test:
`rspec spec/unit/lib/temporal/workflow/task_processor_spec.rb`
> Paginate through empty workflow history pages

- lib/temporal/connection/serializer/failure.rb
- lib/temporal/workflow/errors.rb
- spec/unit/lib/temporal/connection/serializer/failure_spec.rb
- spec/unit/lib/temporal/workflow/errors_spec.rb
The rollout of https://github.com/coinbase/temporal-ruby/pull/214 went well, except one customer was trying to serialize a pathological error that went up to 47MB.
This change will prevent that by falling back to the old serialization path in that case.
New unit tests: 
`rspec spec/unit/lib/temporal/connection/serializer/failure_spec.rb`
`rspec spec/unit/lib/temporal/workflow/errors_spec.rb`
Reworded some error messages, so
Integration tests to check for regressions:
```
USE_ERROR_SERIALIZATION_V2=1 ./bin/worker
./bin/worker
cd examples
rspec ./spec/
```
> Don't serialize huge exceptions

- examples/spec/integration/continue_as_new_spec.rb
Test was not updated in d0f3ad96d20c60736e71b471e5055bbfdfae79af as it should have been when the example header was updated. This fixes that.
> Fix header in example integration test.

- README.md
- lib/temporal/activity/poller.rb
- lib/temporal/worker.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/activity/poller_spec.rb
- spec/unit/lib/temporal/worker_spec.rb
- spec/unit/lib/temporal/workflow/poller_spec.rb
Closes https://github.com/coinbase/temporal-ruby/issues/215
Add sleep before retrying after unsuccessful poll for workflow and activity tasks. Default value is 0 so without extra configs worker will behave in old way. Sleep duration is specified in seconds.
Also add tests for new functionality.
Add docs to `README.md`.
> Add sleep after bad poll

- examples/spec/integration/start_workflow_spec.rb
- lib/temporal/connection/serializer/workflow_id_reuse_policy.rb
- spec/unit/lib/temporal/connection/serializer/workflow_id_reuse_policy_spec.rb
This new workflow ID reuse policy was added with the updated protobuf in #217. While the underlying GRPC connection layer already supports this with that updated proto, this change adds mapping code and tests for actually using it in temporal-ruby.
New unit spec for mapper:
```
bundle exec rpsec spec/unit/lib/temporal/connection/serializer/workflow_id_reuse_policy_spec.rb
```
New example spec:
```
pushd examples
bin/worker # in separate terminal
bundle exec rspecspec/integration/start_workflow_spec.rb:73
popd
```
> Terminate-if-running workflow ID reuse policy

- lib/temporal/connection/grpc.rb
- lib/temporal/connection/interceptors/client_name_version_interceptor.rb
- Add gRPC headers 'client-name' and 'client-version'
- This SDK will identity itself as `community-ruby`
- These headers allow Temporal to collect SDK usage metrics. Adding these headers now will help measuring impact and adoption of the current community-supported SDK vs the new Temporal-supported SDK.
> Send client-name and client-version headers

- examples/README.md
- examples/bin/register_namespace
- examples/spec/integration/search_attributes_spec.rb
- lib/temporal/client.rb
- lib/temporal/connection/grpc.rb
- spec/unit/lib/temporal/client_spec.rb
- spec/unit/lib/temporal/grpc_spec.rb
- spec/unit/lib/temporal/workflow/executor_spec.rb
This makes temporal-ruby compatible with SQL-based enhanced visibility by propagating namespace through the APIs. If no namespace value is specified, the default from the configuration will be used. In clusters with Elastic Search for enhanced visibility, this value will be ignored, but it is required for SQL-based enhanced visibility.
Other tangentially related improvements:
- Some specs failed when run on Windows with the latest versions of Ruby and dependencies. These fixes are minor to get the tests passing in this environment.
- The `examples/bin/register_namespace` script has been made more robust. This can now be run without any arguments to properly provision a newly started up Temporal server with the `ruby-samples` namespace and search attributes. This script also now works with …
> Temporal CLI and SQL-based enhanced visibility compatibility

- lib/temporal/connection/interceptors/client_name_version_interceptor.rb
This fixes https://github.com/coinbase/temporal-ruby/issues/237 (an issue with package loading) introduced in #223.
fyi @mjameswh
> Require version in client name version interceptor

- examples/docker-compose.yml
- examples/dynamic-config.yml
We have tests in CI that sometimes fails because the search attributes cache wasn't updated with the newly registered attributes. The setting added in this PR will force a cache refresh when reading search attributes.
See https://github.com/coinbase/temporal-ruby/pull/241 for more context.
> Set system.forceSearchAttributesCacheRefreshOnRead to true for examples

- lib/temporal/activity/poller.rb
- lib/temporal/worker.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/activity/poller_spec.rb
- spec/unit/lib/temporal/worker_spec.rb
- spec/unit/lib/temporal/workflow/poller_spec.rb
Upstreamed on behalf of @drewhoskins-stripe. Merge conflicts with #216 resolved.
In tests, we need to stop the worker threads from the main thread when we tear down the test case.
This was racing with start if we called it too soon, as was common, for example, if we threw an exception when trying to create a workflow.
Most commonly this resulted in a deadlock:
* stop method begins, shuts down 0 pollers, and sleeps
* start method completes, adding more pollers as part of normal initialization.
* stop method now calls `:wait` on each poller, but since they were added after the shutdown, they had not previously been shut down.
There are other potentially subtle issues, so I'm just throwing start and stop under a mutex.
I also added an assertion to the pollers to catch when this deadlock …
> Make worker.start and worker.stop threadsafe

- examples/activities/long_running_activity.rb
- examples/workflows/long_workflow.rb
- lib/temporal/activity/context.rb
- lib/temporal/activity/poller.rb
- lib/temporal/activity/task_processor.rb
- lib/temporal/configuration.rb
- lib/temporal/metadata.rb
- lib/temporal/metadata/activity.rb
- lib/temporal/scheduled_thread_pool.rb
- lib/temporal/testing/local_activity_context.rb
- lib/temporal/testing/local_workflow_context.rb
- spec/fabricators/activity_metadata_fabricator.rb
- spec/fabricators/grpc/activity_task_fabricator.rb
- spec/fabricators/grpc/record_activity_heartbeat_fabricator.rb
- spec/unit/lib/temporal/activity/context_spec.rb
- spec/unit/lib/temporal/activity/poller_spec.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
- spec/unit/lib/temporal/metadata/activity_spec.rb
- spec/unit/lib/temporal/scheduled_thread_pool_spec.rb
- spec/unit/lib/temporal/workflow/context_spec.rb
In order to reduce load and potential denial of service of the Temporal server, the Go and Java SDKs limit the number of heartbeats sent by activities. This also has cost implications for Temporal Cloud which charges per heartbeat. This change adds this same kind of throttling here.
If no heartbeat has been sent yet, it will still be immediately sent, just like before this change. Any error or cancellation will be returned back to the caller. However, it will schedule a timer at the desired heartbeating interval on a background thread. While this timer is scheduled, any heartbeat payloads will be saved in memory but not actually sent to Temporal server. Once the interval has passed, any the latest saved heartbeat payload will be sent. If there is an unsent heartbeat when an activity …
> Heartbeat throttling

- lib/temporal/connection/serializer/continue_as_new.rb
- spec/unit/lib/temporal/connection/serializer/continue_as_new_spec.rb
Upon continuing as new, the run timeout is being set to the execution timeout. For example, if the run timeout is 21 days and execution timeout is 10 years, this will result in chained executions from a workflow that continues as new timing out if the chain is longer than 21 days.
This change sets the run timeout to the run timeout instead of the execution timeout. Specs have been modified to verify this.
Updated unit test:
```
bundle exec rspec spec/unit/lib/temporal/connection/serializer/continue_as_new_spec.rb
```
> Fix continue as new timeout propagation

- lib/temporal/workflow/context.rb
- spec/unit/lib/temporal/workflow/context_spec.rb
#234 broke local activities because the `Activity::Context` constructor callsite they rely on was not updated. Local activities were also not covered by any specs, which made it easy to miss this. This change passes the correct number of parameters to the constructor and adds a basic spec for local activity invocation.
Fixes #245 
New spec: `bundle exec rspec spec/unit/lib/temporal/workflow/context_spec.rb:100`
> Fix and add spec for local activities

- lib/temporal/client.rb
In the [Temporal client code](https://github.com/coinbase/temporal-ruby/blob/41a8e923e52f62a6727e3ce6ffa2d68090b29439/lib/temporal/client.rb#LL408C5-L410C8), the query_workflow_executions method uses a local variable named filter within the method body but does not accept it as a parameter, causing a NameError to be raised.
The full error message is the following:
"error":"#<NameError: undefined local variable or method `filter' for #<Temporal::Client:0x000000010bca6f00>>"
This method was introduced in https://github.com/coinbase/temporal-ruby/pull/177.
> Add filter to query_workflow_executions method arguments

- examples/spec/integration/initial_search_attributes_spec.rb
- examples/spec/integration/reset_workflow_spec.rb
- examples/spec/integration/upsert_search_attributes_spec.rb
- lib/temporal/client.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/reset_reapply_type.rb
- spec/unit/lib/temporal/client_spec.rb
This PR adds two arguments present on the [`ResetWorkflowExecutionRequest` Protobuf message](https://api-docs.temporal.io/#temporal.api.workflowservice.v1.ResetWorkflowExecutionRequest) to the `Temporal.reset_workflow` API:
- `request_id` (an idempotency key)
- `reset_reapply_type` (used to optionally replay signals when resetting workflows)
This PR also adds integration tests for workflow resets, including tests for each of the above added arguments.
I attempted to make the API changes backwards compatible. However, I'm not sure if the `Temporal.reset_workflow` is used much in production, anyways, because I believe it has been broken ever since [Temporal Server v1.14.0](https://github.com/temporalio/temporal/releases/tag/v1.14.0) made the change that the `request_id` field must not be …
> Add missing arguments to Temporal.reset_workflow and add integration tests for Resets

- lib/temporal/connection/converter/payload/proto_json.rb
- spec/unit/lib/temporal/connection/converter/payload/proto_json_spec.rb
ProtoJSON `data` bytes support w/ [`String#b`](https://apidock.com/ruby/String/b)
https://github.com/coinbase/temporal-ruby/issues/263
`JSON` payload converter does the same [here](https://github.com/coinbase/temporal-ruby/blob/80f00631a0254508e23defac0d50a98af62301ed/lib/temporal/connection/converter/payload/json.rb#L21).
> ProtoJSON safely encode JSON to ASCII-8BIT (String#b)

- lib/temporal/activity/poller.rb
- lib/temporal/activity/task_processor.rb
- lib/temporal/scheduled_thread_pool.rb
- lib/temporal/thread_pool.rb
- lib/temporal/workflow/poller.rb
- spec/unit/lib/temporal/activity/context_spec.rb
- spec/unit/lib/temporal/activity/task_processor_spec.rb
- spec/unit/lib/temporal/scheduled_thread_pool_spec.rb
- spec/unit/lib/temporal/thread_pool_spec.rb
All errors and exceptions coming out of a thread pool job are now logged and sent to the error handler
If any error does reach the top of the stack on a thread pool thread, it will now crash the process rather than silently kill the thread. Because `StandardError` is rescued in the `TaskProcessor`, this impacts only severe errors like `NoMemoryError` or `SecurityError` raised by activity or workflow code, or ordinary error raised due to bugs in temporal-ruby itself.
It's perhaps somewhat controversial to crash the worker process, but `Exception` raised out of user code or unexpected errors in the pollers, task processors, or thread pools, leave the worker in an unknown state, where it's unclear that it can continue to safely process work.
Before this change, when an activity or workflow …
> Improve thread pool error handling

- examples/spec/integration/activity_cancellation_spec.rb
- lib/temporal/workflow/command_state_machine.rb
- lib/temporal/workflow/executor.rb
- lib/temporal/workflow/state_manager.rb
- spec/unit/lib/temporal/workflow/state_manager_spec.rb
This change filters out activity and timer cancellation commands before sending back the result of the workflow task to Temporal server. It does this when those commands are associated with activities or timers that have already been canceled.
Existing code in `future.rb` already ensures that cancellation is a no-op on activity and timer futures that have already completed at that point in workflow execution. However, this doesn't cover all cases where an activity or timer is being canceled in the same workflow task where it is completing or failing. Consider the following scenario:
In an earlier workflow task:
- An activity is scheduled by starting an activity in workflow code
In a later workflow task:
- A signal is received, which has a handler that cancels the activity. This will …
> Remove cancelation commands when underlying futures are closed

- lib/temporal/connection/grpc.rb
Fix task queue type to match enum defined constant
When using `describe_task_queue` api, we run into an error
```
`describe_task_queue': uninitialized constant Temporalio::Api::Enums::V1::TaskQueueType::Workflow (NameError)
```
> Fix task queue type to match enum

- spec/unit/lib/temporal/activity_spec.rb
- spec/unit/lib/temporal/workflow_spec.rb
- temporal.gemspec
Fixes a couple of warnings
- Adds the base64 gem to the gemspec. Starting in Ruby 3.4.0, this will be required since it's moving out of the standard library. For 3.3.0, this is showing up as a warning. See https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/ for more information
- Assertions that specs do not raise a specific error have been made more general to assert that a test raises no error at all. This removes a warning and should make these tests slightly more robust
> Fix warnings

- lib/temporal/configuration.rb
- lib/temporal/connection.rb
- lib/temporal/connection/grpc.rb
- spec/unit/lib/temporal/grpc_spec.rb
Add a config option for a basic gRPC connection retry policy:
``` ruby
config.connection_options = {
retry_connection: true
}
```
That uses a basic policy:
```ruby
{
retryableStatusCodes: ["UNAVAILABLE"],
maxAttempts: 3,
initialBackoff: "0.1s",
backoffMultiplier: 2.0,
maxBackoff: "0.3s"
}
```
There’s also a `retry_policy` option to set a custom policy if you want more control:
``` ruby
config.connection_options = {
retry_policy: {
retryableStatusCodes: ["UNAVAILABLE", "INTERNAL"],
maxAttempts: 5,
initialBackoff: "0.1s",
backoffMultiplier: 2.5,
maxBackoff: "0.7s"
}
}
```
> Add option for gRPC client connection retries

- README.md
> Update README with middleware documentation

- examples/Gemfile
- lib/temporal/concerns/typed.rb
Resolve the following warning before it becomes a bigger issue.
```
[dry-struct] Dry::Struct::Value is deprecated and will be removed in the next major version
/Users/sal/Development/temporal-ruby/lib/temporal/concerns/typed.rb:35:in `generate_struct'
```
Closes https://github.com/coinbase/temporal-ruby/issues/292
> Move off `Dry::Struct::Value` before its removed from `dry-struct`

- lib/temporal/configuration.rb
- lib/temporal/connection/grpc.rb
Attempt to address https://github.com/coinbase/temporal-ruby/issues/295. 
Alter `Temporal::Connection::GRPC` to respect a `:use_error_serialization_v2` option, falling back to the global singleton value if not found, and update `Temporal::Configuration#for_connection` to pass its setting through when creating connections.
It looks like options can already be plumbed through by editing a Temporal::Configuration instance's `connection_options`, but this case seems slightly different because `use_error_serialization_v2` is an explicit setting on the configuration.
> Propagate :use_error_serialization_v2 option to GRPC client

- lib/temporal/testing/local_workflow_context.rb
`continue_as_new` was never implemented in the testing context, so let's raise `NotImplementedError` instead of `NoMethodError` for clarify.
> Mark continue_as_new as not implemented in testing context

- Gemfile
- examples/Gemfile
This PR is a follow-up to https://github.com/coinbase/temporal-ruby/pull/308 that relaxes the gem version constraint from a `~> major.minor.patch` to a `~> major.minor` constraint. This means that any `3.x` version of `google-protobuf` is allowed, as long as the minor version is _at least_ `3.19`.
Doing so makes `bundle` resolve a much newer version of the `grpc` gem (on my machine, it makes it resolve `1.65.1` (released in July 2024) instead of `1.42.0` (released in Dec 2021)).
The older `grpc` gem version `1.42.0` has a known issue that causes build failures on Apple Silicon macOS systems: https://github.com/grpc/grpc/issues/35148. This is fixed in recent versions of the `grpc` gem.
By using a newer version of the `grpc` gem, fresh bundle installs on Apple Silicon computers work without …
> Relax version specifier for 'google-protobuf' to fix build errors on Apple Silicon machines

- README.md
- lib/temporal/activity/poller.rb
- lib/temporal/connection/grpc.rb
- lib/temporal/worker.rb
- spec/unit/lib/temporal/activity/poller_spec.rb
- spec/unit/lib/temporal/grpc_spec.rb
- spec/unit/lib/temporal/worker_spec.rb
This PR exposes the `activity_max_tasks_per_second` option when constructing a new `Temporal::Worker` instance. This setting sets the `max_tasks_per_second` option when making `PollActivityTaskQueue` RPCs to the server, which has the effect of limiting how fast the server will give out activity tasks (both new activities and retries of already-running activities).
This same option is exposed in other SDKs; for example in Java it's available on the `WorkerOptions` struct as [the `setMaxTaskQueueActivitiesPerSecond` option](<https://javadoc.io/doc/io.temporal/temporal-sdk/latest/io/temporal/worker/WorkerOptions.Builder.html#setMaxTaskQueueActivitiesPerSecond(double)>). The doc comment added in this PR was based off of the doc comment in the Java SDK. The semantics of the values …
> Support passing activity task rate limit on worker options
